config/routes.rb
Rails.application.routes.draw do
  get 'cars/search', to: 'cars#index', :as => 'search_page'
  get 'cars/:id/search', to: 'cars#index'
  get 'cars/new', to:'cars#new'
  post 'cars', to:'cars#create'
  get 'cars/:id', to:'cars#show', as: :car
  get 'cars/:id/book', to:'cars#book', as: :book
  #get 'cars/:id/contracts/new', to:'contracts#new'
  get 'contracts/success', to:'contracts#success', as: :success
  post 'cars/:id/book', to:'contracts#create'
  resources :pages do
    collection do
      get :home
    end
  end

  resources :cars do
    collection do
      get :new
    end
  end

  devise_for :users
  root to: 'pages#home', as: :root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    searchkick
    belongs_to :user
    has_many :contracts
    has_many_attached :photos
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?

 #   include PgSearch::Model
 #   pg_search_scope :global_search,
 #   against: [ :model, :description, :address, :category, ],
 #   associated_against: {},
 #   using: {
 #     tsearch: { prefix: true }
 #   }
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars, dependent: :destroy
  has_many :contracts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!") and return
    else
      #@cars = Car.all.where(category:"van")
      @parameter = params[:search].downcase
      Car.reindex
      @cars= Car.search @parameter
      #@cars = Car.all.where("lower(category) LIKE :search OR lower(model) LIKE :search OR lower(description) LIKE :search", search: @parameter)

      @sets = Car.geocoded

      @markers = @sets.map do |car|
        {
          lat: car.latitude,
          lng: car.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { car: car })
        }
      end
    end
  end

  def show
    @car = Car.find(params[:id])
  end

#  def descending_help
 #   respond_to do |format|
 #     format.html {}
 #     format.js
 #   end
#  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

 def book
  @car = Car.find(params[:id])
  @contract = Contract.new
  @contract.user=current_user
  @contract.car=@car

end

  def car_params
    params.require(:car).permit(:model, :description, :price, :category, :address, photos: [])
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
    def new
        @contract=Contract.new
    end

    def create
        @contract=Contract.new()
        @contract.user=current_user
        @contract.car=Car.find(params[:id])
        if @contract.save
          redirect_to success_path
        else
         render :new
        end
      end

      def success
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @lastest_cars = Car.order(id: :desc)

    @all_cars = Car.all
    categories = []
    @counts = Hash.new(0)
    @all_cars.each do |car|
      categories << car.category
      categories.each { |name| @counts[name] += 1 }
    end

    @first_car = Car.find_by(category: @counts.keys[0])
    @second_car = Car.find_by(category: @counts.keys[1])
    @third_car = Car.find_by(category: @counts.keys[2])
    @fourth_car = Car.find_by(category: @counts.keys[3])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_info_window.html.erb
<% if car.photos.attached? %>
  <%= cl_image_tag car.photos.first.key, height: 200, crop: :scale, class: 'card-img-top' %>
<% else %>
  <img class="card-img-top" src="https://d1zgdcrdir5wgt.cloudfront.net/media/vehicle/images/7c0IdMWbT7WJG_X4DFCZuw.1440x700.jpg" alt="Card image cap">
<% end %>

<h2><%= car.model %></h2>
<p><%= car.address %></p>
<p><%= car.price %></p>

app/views/cars/book.html.erb
<div class="container mb-5">
  <h1 class="title">One Last Step...</h1>

  <div class="card" style="width: 40%;">
  <% if @car.photos.attached? %>
    <%= cl_image_tag @car.photos.first.key, crop: :scale, class: 'card-img-top' %>
  <% else %>
    <img class="card-img-top" src="https://d1zgdcrdir5wgt.cloudfront.net/media/vehicle/images/7c0IdMWbT7WJG_X4DFCZuw.1440x700.jpg" alt="Card image cap">
  <% end %>
    <div class="card-body">
    <h5 class="card-title"><%= @car.model %></h5>
    <p class="card-text"><%= @car.description %></p>
    </div>
  <ul class="list-group list-group-flush">
  <li class="list-group-item"><%= @car.category %></li>
  <li class="list-group-item">Price: <%= @car.price %> /Day</li>
  <li class="list-group-item"><%= @car.address %></li>
  </ul>
  <div class="card-body d-flex justify-content-between">
  <%= button_to 'Book' ,{:controller => 'contracts', :action => 'create', :user=> current_user, :car => @car}, {:method => :post, class: "btn btn-success"}%>
  <%= link_to "Cancel", "/pages/home", class: "btn btn-secondary" %>
  </div>
</div>
</div>

app/views/cars/index.html.erb
<div class="cards-container">
<h1>Search Results for "<%= @parameter %>" </h1>
<br/>
<div class="btn-group">
  <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sorted By
  </button>

<!--  <% def ascending() %>
    <%= render "/shared/ascendingcars" %>
  <% end %>

  <% def descending() %>
    <%= render "/shared/descendingcars" %>
  <% end %>
-->


  <div class="dropdown-menu">


  <%= button_tag "Price Down", type: 'button', onclick: "descending()", class: 'dropdown-item' %>
  <%= button_tag "Price Up ", type: 'button', onclick: "ascending()", class: 'dropdown-item' %>
<!--
     <a class="dropdown-item" onclick="descending()">Price Down</a>
    <a class="dropdown-item" onclick="ascending()">Price Up </a>
    -->
  </div>
  <div style="position:relative;top:2px;left:20px",class="container">
  <%= form_tag(search_page_path, :method => "get") do %>
    <div class="input-group md-form form-sm form-2 pl-0" >
      <%= search_field_tag :search, params[:search], placeholder: "New Search", class: "form-control border border-primary" %>
     <!-- <div class="input-group-btn">--> 
      <span class="p-1 mb-1 bg-light">
      <%= button_tag "", :class => 'btn fas fa-search text-grey ',:name => nil%>
      </span>
    
    </div>
    <% end %>
    </div>
    

</div>
  <div>
    <div id="content" class="container">
    <%= render "/shared/ascendingcars" %>
    </div>

  <!--
  <%= render "shared/ascendingcars" if @ascendingcars %>
  <%= render "shared/descendingcars" unless @ascendingcars %>
  -->


  </div>

</div>

app/views/cars/new.html.erb
<div class="container">
  <h1 class="title">Rent your car!</h1>
  <%= simple_form_for @car do |f| %>
    <div class="form-group ml-1 mb-5 px-5">
      <%= f.input :model, class: 'form-control' %>
      <br>
      <%= f.input :category, class: 'form-control'%>
      <br>
      <%= f.input :description %>
      <br>
      <%= f.input :price, as: :numeric %>
      <br>
      <%= f.input :address %>
      <br>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <%= link_to "Cancel", "/pages/home", class: "btn btn-light" %>
    </div>
  <% end %>
</div>

app/views/cars/show.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @car.photos.each.with_index do |photo, i| %>
      <li data-target="#myCarousel" data-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
    <% end %>
  </ol>

  <div class="carousel-inner">
    <% @car.photos.each.with_index do |photo, i| %>
      <div class="carousel-item <%= 'active' if i == 0 %>">
        <%= cl_image_tag photo.key %>
      </div>
    <% end %>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="container">
  <h1 class="title"><%= @car.model %></h1>
  <h3 class="description"><%= @car.description %></h3>
  <h2 class="price">$<%= @car.price %> / day</h2>
  <div class="d-flex justify-content-between mb-2">
  <%= link_to "Book this car!", book_path, class: "btn btn-primary" %>
  <%= link_to "Go back for a new search", search_page_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/contracts/success.html.erb
<div class="container">
  <h1 class="title">Your order has been received!</h1>
      <%= link_to "Back", "/pages/home", class: "btn btn-grey" %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1474471981552-e3084590b868?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <h1><center><strong>Rent a Car Now</strong></center></h1>
    <br/>
    <%= form_tag(search_page_path, :method => "get") do %>
    <div class="input-group md-form form-sm form-2 pl-0">

      <%= search_field_tag :search, params[:search], placeholder: "Search anything", class: "form-control my-0 py-1 red-border" %>
     <div class="input-group-btn">
      <%= button_tag "Search", :class => 'btn btn-blue',:name => nil%>
    </div>

    </div>
    <% end %>
  </div>
</div>

<div class="cards-container">
  <h2><strong>Top Categories</strong></h2>

  <div class="card-deck">
    <div class="col-sm-12 col-lg-6 col-xl-3 mb-5">
      <div class="card">
        <% if @first_car.photos.attached? %>
          <%= cl_image_tag @first_car.photos.first.key, crop: :scale, class: 'card-img-top' %>
        <% else %>
          <img class="card-img-top" src="https://resources.turo.com/f/81934/424x318/df302dea72/category-carousel_luxury-2x.jpg" alt="Image">
        <% end %>
        <div class="card-body">
          <a class="card-link" href="https://aircns.herokuapp.com/cars/search?search=<%=@counts.keys[0]%>"><%=@counts.keys[0]%></a>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-lg-6 col-xl-3 mb-5">
      <div class="card">
        <% if @second_car.photos.attached? %>
          <%= cl_image_tag @second_car.photos.first.key, crop: :scale, class: 'card-img-top' %>
        <% else %>
          <img class="card-img-top" src="https://resources.turo.com/f/81934/424x318/7f4e44231c/category-carousel_classic-2x.jpg" alt="Image">
        <% end %>
        <div class="card-body">
          <a class="card-link" href="https://aircns.herokuapp.com/cars/search?search=<%=@counts.keys[1]%>"><%=@counts.keys[1]%></a>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-lg-6 col-xl-3 mb-5">
      <div class="card">
        <% if @third_car.photos.attached? %>
          <%= cl_image_tag @third_car.photos.first.key, crop: :scale, class: 'card-img-top' %>
        <% else %>
          <img class="card-img-top" src="https://resources.turo.com/f/81934/424x318/288f0f5045/category-carousel_convertible-2x.jpg" alt="Image">
        <% end %>
        <div class="card-body">
          <a class="card-link" href="https://aircns.herokuapp.com/cars/search?search=<%=@counts.keys[2]%>"><%=@counts.keys[2]%></a>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-lg-6 col-xl-3 mb-5">
      <div class="card">
        <% if @fourth_car.photos.attached? %>
          <%= cl_image_tag @fourth_car.photos.first.key, crop: :scale, class: 'card-img-top' %>
        <% else %>
          <img class="card-img-top" src="https://resources.turo.com/f/81934/424x318/3fc8dbffa5/category-carousel_minivan-2x.jpg" alt="Image">
        <% end %>
        <div class="card-body">
          <a class="card-link" href="https://aircns.herokuapp.com/cars/search?search=<%=@counts.keys[3]%>"><%=@counts.keys[3]%></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="cards-container">
  <h2><strong>Newest Offers</strong></h2>
  <div class="row">
    <% @lastest_cars.limit(2).each do |car| %>
        <div class="col-sm-12 col-md-6 mb-5">
          <div class="card">
            <%= cl_image_tag car.photos.first.key, crop: :scale, class: 'card-img-top' %>
              <div class="card-infos">
                <h5 class="card-title"><%= car.model %></h5>
                <h5 class="card-title">$<%= car.price %> / day</h5>
              </div>
              <div class="center">
              <%= button_to "Book Now!", book_path(car), class: "btn btn-blue" %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/shared/_ascendingcars.html.erb
<div class="row">
<div class="col-5">
<% @cars.sort_by(&:price).each do |car| %>
      
       <%= link_to car_path(car),class:"custom-card" do %>
       <div class="card mt-4" >
        <% if car.photos.attached? %>
          <%= cl_image_tag car.photos.first.key, height: 200, crop: :scale, class: 'card-img-top' %>
        <% else %>
          <img class="card-img-top" src="https://d1zgdcrdir5wgt.cloudfront.net/media/vehicle/images/7c0IdMWbT7WJG_X4DFCZuw.1440x700.jpg" alt="Card image cap">
        <% end %>
        <div class="card-body">
        <h3 class="card-title"><strong> <%= car.model %></strong> </h3>
        <h5 class="card-text"> $<%= car.price %> /Day</h5>
        <h5 class="card-text"> Address: <%= car.address %> </h5>
       
        </div>
        </div>
        <% end %>

<% end %>
</div>
<div class="col-7">
<div id="map"
       style="width: 100%; height: 600px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>
</div>

app/views/shared/_descendingcars.html.erb
<div class="row">
<% @cars.sort_by(&:price).reverse!.each do |car| %>
    <div class="col-sm-4">
       <div class="card mt-4">
        <img class="card-img-top" src="https://d1zgdcrdir5wgt.cloudfront.net/media/vehicle/images/7c0IdMWbT7WJG_X4DFCZuw.1440x700.jpg" alt="Card image cap">
        <div class="card-body">
        <h5 class="card-title"> <%= car.model %> </h5>
        <p class="card-text"> <%= car.description %> </p>
        <p class="card-text"><strong> <%= car.price %> </strong></p>
        </div>
        </div>
        </div>
<% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    RENTERR © 2020. All rights reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/pages/home", class: "navbar-brand" do %>
    <%= image_tag 'renterr_logo.jpg' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "List your car", "/cars/new", class: "nav-link" %>
        </li>
        <li> &nbsp; &nbsp; &nbsp; </li>
        <li class="nav-item dropdown">
          <%= image_tag 'avatar.jpg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Your cars", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>